# Настройки подключения к PostgreSQL для DataStorage
# Используется как: postgresql+psycopg2://<user>:<password>@<host>:5432/<dbname>
[database]
url = "postgresql+psycopg2://postgres:1223334444F@localhost:5432/corpus_DB"

DB_HOST = "localhost"
DB_USER = "postgres"
DB_PASSWORD = "1223334444F"
DB_NAME = "corpus_DB"
